server:
  port: 8088

spring:
  profiles:
    active: dev
  datasource:
    # MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/maku_generator?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: maku
    password: 123456
    # Oracle
    #    driver-class-name: oracle.jdbc.OracleDriver
    #    url: jdbc:oracle:thin:@localhost:1521:xe
    #    username: maku_generator
    #    password: maku_generator
    # SQLServer
    #    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #    url: jdbc:sqlserver://localhost:1433;DatabaseName=maku_generator;encrypt=true;trustServerCertificate=true
    #    username: sa
    #    password: 123456@maku
    # postgresql
    #    driver-class-name: org.postgresql.Driver
    #    url: jdbc:postgresql://localhost:5432/postgres
    #    username: postgres
    #    password: 123456
    # 达梦8
#    driver-class-name: dm.jdbc.driver.DmDriver
#    url: jdbc:dm://localhost:5236/maku_generator?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
#    username: maku_generator
#    password: 12345678
    # 人大金仓
#    driver-class-name: com.kingbase8.Driver
#    url: jdbc:kingbase8://localhost:54321/maku_generator?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
#    username: system
#    password: 123456

# 需要指定对应的模板
generator:
  template: /template/maku-boot

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: net.maku.generator.entity
  global-config:
    db-config:
      id-type: AUTO
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE